version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Hello World from circleci"
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Testing Hello World from Circle CI"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
        requires:
          - build
